export const propertyHeaders = [
    { header: "Property ID", accessorKey: "property_id" },
    { header: "Name", accessorKey: "name" },
    { header: "Street Address", accessorKey: "street_address" },
    { header: "Locality", accessorKey: "locality" },
    { header: "City", accessorKey: "city" },
    { header: "State", accessorKey: "state" },
    { header: "Pincode", accessorKey: "pincode" },
    { header: "Country", accessorKey: "country" },
    { header: "Property Type", accessorKey: "property_type" },
    { header: "Default Monthly Maintenance Fee", accessorKey: "default_monthly_maintenance_fee" },
    { header: "Maintenance Fee Per Sqft", accessorKey: "maintenance_fee_per_sft" },
    { header: "Meta Status", accessorKey: "meta_status" },
    { header: "Is Deleted", accessorKey: "is_deleted" },
    { header: "Created At", accessorKey: "created_at" },
    { header: "Updated At", accessorKey: "updated_at" },
    { header: "Meta Data", accessorKey: "meta_data" },
    { header: "Status", accessorKey: "status" },
    { header: "Total Documents Count", accessorKey: "total_documents_count" },
    { header: "Total Documents Size (Bytes)", accessorKey: "total_documents_size_bytes" },
    { header: "Allowed Documents Size (Bytes)", accessorKey: "allowed_documents_size_bytes" },
]