export const userHeaders = [
    { header: "User ID", accessorKey: "user_id" },
    { header: "Email", accessorKey: "email" },
    { header: "First Name", accessorKey: "first_name" },
    { header: "Last Name", accessorKey: "last_name" },
    { header: "Phone Number", accessorKey: "phone_number" },
    { header: "User Type", accessorKey: "user_type" },
    { header: "Meta Status", accessorKey: "meta_status" },
    { header: "Is Deleted", accessorKey: "is_deleted" },
    { header: "Created At", accessorKey: "created_at" },
    { header: "Updated At", accessorKey: "updated_at" },
    { header: "Meta Data", accessorKey: "meta_data" },
    { header: "Status", accessorKey: "status" },
    { header: "Supabase Auth ID", accessorKey: "supabase_auth_id" },
    { header: "Secondary Email", accessorKey: "secondary_email" },
    { header: "Is ID Verified", accessorKey: "is_id_verified" },
    { header: "Secondary Phone Number", accessorKey: "secondary_phone_number" },
    { header: "Address", accessorKey: "address" },
    { header: "ID Number", accessorKey: "id_number" },
    { header: "ID Type", accessorKey: "id_type" },
];